backend/controllers/GeneratorController.php
<?php

namespace backend\controllers;


use common\component\helpers\CommonHelper;
use common\component\helpers\GeneratorHelper;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use Yii;
use yii\console\Controller;

class GeneratorController extends Controller
{

    /**
     * generate ngLoader template from svg string
     * @return array
     */
    public function actionGenngloadertemplate()
    {

        $request = Yii::$app->request;
        $submit = $request->post('submit');
        $svg = $request->post('svg');

        $model = new \stdClass();
        $model = (object)[
            'svg' => '',
            'result' => ''
        ];
        if ($submit) {

            foreach (preg_split("/((\r?\n)|(\r\n?))/", $svg) as $line) {
                // do stuff with $line
                $line = str_replace('"', '\"', $line);
                $line = '" ' . $line . '\n" +';

                $model->svg .= $line . PHP_EOL;
            }

            $model->bg_color = $request->post('bg_color');
            $model->result = $this->renderPartial('ng-loader-template', ['model' => $model]);

        }
        else {
            $model->bg_color = 'rgba(214, 214, 214, 0.5)';
        }


        return $this->render('generator', ['model' => $model]);
    }

    public function actionScanandconvertoldversion()
    {

        $scanDirs = [
            Yii::$app->params['oldControllerDir'],
            Yii::$app->params['oldVendorDir']
        ];
        $saveOutputTo = Yii::$app->params['newOutputDir'];

        // generate the files which has the name end with this string, leave empty if you want to generate all
        $genOnlyFileHasSuffixNames = []; //example: ['Commons', ...]

        foreach ($scanDirs as $scanDir) {
            //find file recursive folder
            foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($scanDir)) as $filePath) {
                $fileName = pathinfo($filePath, PATHINFO_FILENAME);
                var_dump($fileName);

                if (is_file($filePath)) {
                    if (empty($genOnlyFileHasSuffixNames))
                        GeneratorHelper::updateFile($filePath, $saveOutputTo);
                    else {
                        foreach ($genOnlyFileHasSuffixNames as $nameSuffix) {
                            if (strpos($filePath, $nameSuffix) !== false)
                                GeneratorHelper::updateFile($filePath, $saveOutputTo);
                        }
                    }

                }
            }
        }

    }

    /**
     * gen layout angularjs.php --> angularjs_minify.php
     */
    public function actionGenminangularlayout()
    {

        $scanFile = Yii::$app->params['viewLayoutDir'] . DIRECTORY_SEPARATOR . 'angularjs.php';
        $saveTo = Yii::$app->params['viewLayoutDir'] . DIRECTORY_SEPARATOR . 'angularjs_minify.php';

        $content = file_get_contents($scanFile);

        $re = "/src\\s*=\\s*\"(.+)(\\/(.+)\\.js)\"/";
        $replace = "src=\"<?= \Yii::\$app->request->BaseUrl ?>/angularjs/build/live/$3.min.js\"";
        $newContent = preg_replace($re, $replace, $content);

        //overwrite the new content
        file_put_contents($saveTo, $newContent);
    }

    /**
     * it will generate three file example: abcController.js, abc.html, abcService.js, abc.css
     */
    public function actionGenangularcombofiles()
    {
        $request = Yii::$app->request;
        $name = $request->post('name', '');
        $include_path = "";
        $route_state_entry = "";
        $routeStateDeps = [];
        $main_entry =  "";

        if ($name != "") {


            $dirPath = sprintf(Yii::$app->params['controllerDirFormat'] . DIRECTORY_SEPARATOR, $name);
            $listCamelCaseSuffixes = [
                'Controller.js', 'Service.js'
            ];

            $listSuffixes = [
                '.css', '.html'
            ];

            $camelCaseName = CommonHelper::dashesToCamelCase($name);

            foreach ($listCamelCaseSuffixes as $suffix) {
                //create directories based on the given path if they do not exist
                if (!file_exists($dirPath)) {
                    mkdir($dirPath, 0777, true);
                }

                $filePath = $dirPath . $camelCaseName . $suffix;
                file_put_contents($filePath, '');
            }

            foreach ($listSuffixes as $suffix) {
                //create directories based on the given path if they do not exist
                if (!file_exists($dirPath)) {
                    mkdir($dirPath, 0777, true);
                }

                $filePath = $dirPath . $name . $suffix;
                file_put_contents($filePath, '');
            }

            $include_path = "<script src=\"<?= \Yii::\$app->request->BaseUrl ?>/angularjs/app/controllers/$name/{$camelCaseName}Controller.js\"></script>";

            $route_state_entry = $this->renderPartial('_route-states-entry', ['name' => $name, 'camelCaseName' => $camelCaseName, 'routeStateDeps' => $routeStateDeps]);

            $main_entry = "<div ui-view=\"$name\" ng-show=\"\$state.includes('main.$name')\"></div>";
        }

        return $this->render('angular-combo-files', [
            'include_path' => $include_path,
            'route_state_entry' => $route_state_entry,
            'main_entry' => $main_entry
        ]);
    }

    public function actionFormatstaticdataarray()
    {
        $scanDir = Yii::$app->params['dirInput'];

        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($scanDir)) as $filePath) {
            //$fileName = pathinfo($filePath, PATHINFO_FILENAME);

            if (is_file($filePath)) {
                $content = file_get_contents($filePath);

                $re = "/array\\(\"text\" => \"([\\w-\\s]+)\", \"([\\w-\\s]+)\" => \"([\\w-\\s]+)\"\\)/";
                $replace = "\"$3\" => \"$1\"";
                $newContent = preg_replace($re, $replace, $content);

                //overwrite the new content
                file_put_contents($filePath, $newContent);

            }
        }


    }

    public function actionQuickbuildsign()
    {
        /*
        $skinStructure = [
            ["(0,0)(350,350)", "(350,0)(700,350)", "(700,0)(1050,350)"],
            ["(0,350)(350,700)", "(350,350)(700,700)", "(700,350)(1050,700)"],
            ["(0,700)(350,1050)", "(350,700)(700,1050)", "(700,700)(1050,1050)"]

        ];
        //Yii::info('addSampleSkin...');
        $skin_id = GeneratorHelper::addSampleSkin($skinStructure);
        */
        GeneratorHelper::addSamplePublishedSign(Member::I_SIGN_TYPE_ID);
        //GeneratorHelper::addSampleItemVariant();
        var_dump('done');
    }

    /**
     * Gen multi-steps page
     */
    public function actionGenmultisteppage()
    {

        $request = Yii::$app->request;

        if (isset($_POST['steps'])) {
            $steps = array_filter($_POST['steps'], function($step){ return trim($step['name']) != ''; });
            $pageName = $request->post('pageName');

            // controller directory
            $dirPath = sprintf(Yii::$app->params['controllerDirFormat'] . DIRECTORY_SEPARATOR, $pageName);
            if (!file_exists($dirPath)) {
                mkdir($dirPath, 0777, true);
            }
            //controller name
            $ctrlName = CommonHelper::dashesToCamelCase($pageName);

            $step1_name = "";
            if(count($steps) > 0) $step1_name = $steps[0]['name'];
            $ctrlContent = $this->renderPartial('multi-steps-page-tpl-ctrl', [
                'ctrlName' => $ctrlName,
                'step1_name' => $step1_name
            ]);

            //controller js path
            $filePath = CommonHelper::sanitizePath($dirPath . DIRECTORY_SEPARATOR . $ctrlName . 'Controller.js');
            //save controller js file

            file_put_contents($filePath, $ctrlContent);

            $ctrlContent = $this->renderPartial('multi-steps-page-tpl-ctrl-html', [
                'ctrlName' => $ctrlName,
                'steps' => $steps
            ]);
             //controller html path
            $filePath = CommonHelper::sanitizePath($dirPath . DIRECTORY_SEPARATOR . $pageName . '.html');
            //save controller html file
            file_put_contents($filePath, $ctrlContent);

            //generate the css file of the controller
            $filePath = CommonHelper::sanitizePath($dirPath . DIRECTORY_SEPARATOR . $pageName . '.css');
            //save controller html file
            file_put_contents($filePath, '');

            $stepCount = count($steps);
            $routeStateDeps = [];

            $gotoStepName = '';
            foreach ($steps as $index=>$step) {
                $step = (object)$step;

                $stepButtons = [];

                if(trim($step->name) != ''){
                    $l = explode(',', $step->buttons);
                    if(!empty($l)) {
                        $_d = [];
                        foreach($l as $btnName){
                            if(trim($btnName) != ''){
                                $_d[CommonHelper::dashesToCamelCase($btnName)] = $btnName;
                            }

                        }
                        if(!empty($_d)) {
                            $stepButtons = $_d;
                        }
                    }

                    if($index == $stepCount-1 && $index > 0){
                        $gotoStepName = $steps[$index-1]['name'];
                    }elseif($index < $stepCount-1){
                        $gotoStepName = $steps[$index+1]['name'];
                    }

                    $dirFieldsJsTemplate = 'multi-steps-page-tpl-dir-fields';
                    $dirFieldsHtmlTemplate = 'multi-steps-page-tpl-dir-fields-html';

                    if($step->formType == 'icon'){
                        $dirFieldsJsTemplate = 'multi-steps-page-tpl-dir-icon';

backend/views/generator/_route-states-entry.php
//===========================================1:BEGIN: <?php echo $camelCaseName ?> ========================================================
.state('<?php echo $name ?>', {
    url: '/<?php echo $name ?>/:acc_id/mtype={mtype}/oid={oid}/ovid={ovid}',
    controller: '<?php echo $camelCaseName ?>Controller',
    templateUrl: _yii_app.controllerPath + '/<?php echo $name ?>/<?php echo $name ?>.html',
    data: {
        css: [
            _yii_app.angularPath + '/app/controllers/<?php echo $name ?>/<?php echo $name ?>.css'
        ], requiresLogin: true
    },
    resolve: { // Any property in resolve should return a promise and is executed before the view is loaded
        deps: ['$ocLazyLoad', function ($ocLazyLoad) {
            // you can lazy load files for an existing module
            return $ocLazyLoad.load({
                name: 'zwenGlobal',
                files: [
                    _yii_app.controllerPath + '/<?php echo $name ?>/<?php echo $camelCaseName ?>Controller.js',
                    //_yii_app.controllerPath + '/livePath/<?php echo $camelCaseName ?>Controller.min.js'<?php foreach($routeStateDeps as $deps){ echo "
                    $deps"; }?>

                ]
            });
        }]
    }

})
//===========================================1:END: <?php echo $camelCaseName ?> ========================================================

backend/views/generator/angular-combo-files.php
<?php use yii\helpers\Url; ?>
<link rel="stylesheet" href="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/lib/codemirror.css') ?>">
<link rel="stylesheet" href="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldgutter.css') ?>">
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/lib/codemirror.js') ?>"></script>

<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldcode.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldgutter.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/brace-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/xml-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/markdown-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/comment-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/javascript/javascript.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/xml/xml.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/markdown/markdown.js') ?>"></script>

<script id="script">
    /*
     * Demonstration of code folding
     */
    window.onload = function() {
        var area_html = document.getElementById("myUrl");
        var area_script = document.getElementById("code");
        var area_html_main_entry = document.getElementById("main_entry");

        //editor.foldCode(CodeMirror.Pos(13, 0));
        var editor_html = CodeMirror.fromTextArea(area_html, {
            mode: "text/html",
            lineNumbers: true,
            lineWrapping: true,
            extraKeys: {"Ctrl-Q": function(cm){ cm.foldCode(cm.getCursor()); }},
            foldGutter: true,
            gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
        });
        editor_html.setSize(1200, 50);

        var editor_html2 = CodeMirror.fromTextArea(area_html_main_entry, {
            mode: "text/html",
            lineNumbers: true,
            lineWrapping: true,
            extraKeys: {"Ctrl-Q": function(cm){ cm.foldCode(cm.getCursor()); }},
            foldGutter: true,
            gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
        });

        editor_html2.setSize(1200, 50);

        var editor = CodeMirror.fromTextArea(area_script, {
            mode: "javascript",
            lineNumbers: true,
            lineWrapping: true,
            extraKeys: {"Ctrl-Q": function(cm){ cm.foldCode(cm.getCursor()); }},
            foldGutter: true,
            gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
        });
        editor.setSize(1200, 500);

    };
</script>

<form action="<?php yii\helpers\Url::toRoute('generator/genangularcombofiles') ?>" method="post">
    <label>Name:</label> <input type="text" style="width: 300px; height: 25px;" name="name" />
    <input type="submit" value="submit">
    <br/>
</form>


<textarea style="display: none" id="myUrl"><?php echo htmlspecialchars($include_path) ?></textarea>

<br>
Put below line into /frontend/web/angularjs/app/controllers/main/main.html
<textarea id="main_entry"><?php echo htmlspecialchars($main_entry) ?></textarea>

<br>
Put below line into /frontend/web/angularjs/app/apps/routes-states.js
<textarea id="code"><?php echo htmlspecialchars($route_state_entry) ?></textarea>

backend/views/generator/gen-combo-toolbars.php
<?php use yii\helpers\Url; ?>


<?php echo yii\base\View::render('//layouts/global-settings', ['app' => \Yii::$app]) ?>

<script src="<?= Url::to('@web/angularjs/lib/angular-1.3.14/angular.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/angular-1.3.14/angular-loader.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/angular-1.3.14/angular-resource.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/angular-1.3.14/angular-sanitize.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/vendor/ui-codemirror/src/ui-codemirror.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/ui-bootstrap-tpls-0.11.2.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/vendor/angular-ui-router/release/angular-ui-router.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/angular-1.3.14/angular-route.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/vendor/a0-angular-storage/dist/angular-storage.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/ui-router-extras/ct-ui-router-extras.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/vendor/angular-ui-utils/ui-utils.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/lib/vendor/dialog/dialogs.min.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/services/ssHelper.js') ?>"></script>

<link rel="stylesheet" href="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/lib/codemirror.css') ?>">
<link rel="stylesheet" href="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldgutter.css') ?>">
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/lib/codemirror.js') ?>"></script>


<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldcode.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/foldgutter.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/brace-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/xml-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/markdown-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/addon/fold/comment-fold.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/javascript/javascript.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/xml/xml.js') ?>"></script>
<script src="<?= Url::to('@web/angularjs/app/css/ss/js/codemirror5.2/mode/markdown/markdown.js') ?>"></script>

<style>
    .row {
        margin-top: 20px;
    }
</style>

<div ng-controller="MyController">

    <form action="<?php yii\helpers\Url::toRoute('generator/genmultisteppage') ?>" method="post" class="form-inline">

        <div class="navbar"></div>


        <div class="row">
            <label>Generate from icon path:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.iconName" class="form-control" style="width: 672px">
            </div>

            <label>Generate icon for collection/group/item by red/green/blue</label>:</label>
            <input type="checkbox" ng-model="formInfo.is_gen_icon" />

        </div>

        <!-- Collection -->
        <div class="row">
            <div class="form-group">
                <input type="text" ng-model="formInfo.collection.oid" class="form-control" placeholder="ID" style="width:50px;">
            </div>
            <label>Collection Name:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.collection.name" class="form-control">
            </div>
            <label for="buttonNames">Extension:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.collection.ext" class="form-control">
            </div>
            <label for="formType">Support Ext:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.collection.supportExt" class="form-control">
            </div>
        </div>
        <!-- Collection -->

        <!-- Group -->
        <div class="row">
            <div class="form-group">
                <input type="text" ng-model="formInfo.group.oid" class="form-control" placeholder="ID" style="width:50px;">
            </div>
            <label>Group Name:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.group.name" class="form-control">
            </div>
            <label for="buttonNames">Extension:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.group.ext" class="form-control">
            </div>
            <label for="formType">Support Ext:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.group.supportExt" class="form-control">
            </div>
        </div>
        <!-- Group -->

        <!-- Item -->
        <div class="row">
            <div class="form-group">
                <input type="text" ng-model="formInfo.item.oid" class="form-control" placeholder="ID" style="width:50px;">
            </div>
            <label>Item Name:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.item.name" class="form-control">
            </div>
            <label for="buttonNames">Extension:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.item.ext" class="form-control">
            </div>
            <label for="formType">Support Ext:</label>

            <div class="form-group">
                <input type="text" ng-model="formInfo.item.supportExt" class="form-control">
            </div>
        </div>
        <!-- Item -->


    </form>
    <div class="navbar"></div>
    <div class="form-group">
        <button ng-click="submit()" class="btn btn-success">Submit</button>
    </div>


    <br>
    Put below line into /frontend/models/ObjectToolbar.php
    <textarea id="main_entry" ng-model="main_entry" ui-codemirror="{ onLoad : cm1_onLoad }" ui-codemirror-opts="main_entry_opts" ui-refresh='main_entry'></textarea>

    <br>
    Put below line into /frontend/web/angularjs/app/apps/routes-states.js
    <textarea id="code" ng-model="route_state_entry" ui-codemirror="{ onLoad : cm2_onLoad }" ui-codemirror-opts="route_state_entry_opts" ui-refresh='route_state_entry_opts'></textarea>

</div>


<script>
    var genApp = angular.module('generatorApp', ['ui.bootstrap', 'ssFactories', 'ui.codemirror', 'ui.utils', 'dialogs.main']);

    genApp.controller('MyController', ['$scope', '$timeout', 'ssHelper', function ($scope, $timeout, ssHelper) {
        $scope.formInfo = {
            iconName: 'aimp_mirror.jpg',
            is_gen_icon: true,

            collection: { name: '', ext: '', supportExt: ''},
            group: { name: '', ext: '', supportExt: ''},
            item: { name: '', ext: '', supportExt: ''}
        }

        $scope.cm1_onLoad = function (_editor) {
            console.log('loaded1')
            _editor.setSize(1200, 50)
        }
        $scope.cm2_onLoad = function (_editor) {
            console.log('loaded2')
            _editor.setSize(1200, 500)
        }

        $scope.submit = function () {
            ssHelper.post('/generator/Gencombotoolbars', {
                formInfo: $scope.formInfo
            }).then(function (response) {
                $scope.main_entry = response.data.main_entry
                $scope.main_entry_opts = {
                    mode: "application/x-httpd-php",
                    lineNumbers: true,
                    lineWrapping: true,
                    extraKeys: {
                        "Ctrl-Q": function (cm) {
                            cm.foldCode(cm.getCursor());
                        }
                    },
                    foldGutter: true,
                    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
                }

                $scope.route_state_entry = response.data.route_state_entry;
                $scope.route_state_entry_opts = {
                    mode: "javascript",
                    lineNumbers: true,
                    lineWrapping: true,
                    extraKeys: {
                        "Ctrl-Q": function (cm) {
                            cm.foldCode(cm.getCursor());
                        }
                    },
                    foldGutter: true,
                    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
                }
            });
        };
    }]);

    angular.element(document).ready(function () {
        angular.bootstrap(document, ['generatorApp']);
    });
</script>

backend/views/generator/generator.php
<form name="form" action="<?php yii\helpers\Url::toRoute('generator/genngloadertemplate') ?>" method="post">
    
    <table>
        <tr>
            <td><span>SVG</span></td>
            <td>
                <textarea name="svg" style="width: 600px; height: 350px;" value="<?php echo $model->svg ?>"></textarea>
            </td>
        </tr>

        <tr>
            <td><span>Background Color</span></td>
            <td>
                <input name="bg_color" type="text" style="width: 200px" value="<?php echo $model->bg_color ?>">
            </td>
        </tr>
    </table>
    <input type="submit" name="submit" value="submit">
</form>

<br>

<span>Result:</span>
<br>
<textarea style="width: 700px; height: 600px;"><?php echo $model->result ?></textarea>

backend/views/generator/multi-steps-page-tpl-ctrl-html.php
<div id="container">

	<div id="header">
		<auth-user-top-nav></auth-user-top-nav>
	</div>
	<!-- /header -->

	<div id="main" holder="loading">

		<div id="content">
			<div class="content_inner" style="position: relative">
                <?php foreach($steps as $step):?><<?php echo $step['name'] ?> step="step" remote="remote" ng-show="step.name == '<?php echo $step['name'] ?>'" class="fx-fade-right plain_info" style="position: absolute"></<?php echo $step['name'] ?>>
            <?php endforeach;?>

            </div>
		</div>
		<!-- content -->

		<homeboard></homeboard>

		<div class="clr"></div>
	</div>
	<!-- /main -->
	<div class="clr"></div>
</div>

backend/views/generator/multi-steps-page-tpl-ctrl.php
angular.module('zwenGlobal').controller('<?php echo $ctrlName ?>Controller', function ($rootScope, $scope, $state, $stateParams, $timeout, dialogs, ssHelper) {

    $scope.step = {name: '<?php echo $step1_name ?>'}

});

backend/views/generator/multi-steps-page-tpl-dir-fields.php
app.directive('<?php echo $directiveName ?>', function ($timeout, $ocLazyLoad, dialogs, ssHelper) {
    return {
        restrict: 'E',
        templateUrl: _yii_app.controllerPath + '/<?php echo $pageName?>/<?php echo $step->name?>.html',
        bindToController: true,
        scope: {step: '='},
        controller: function ($scope, $stateParams) {
            //$ocLazyLoad.load(_yii_app.controllerPath + '/<?php echo $pageName?>/<?php echo $step->name?>.css');
            $scope.bodyLoader = false;
            $scope.getData = function(){

            }
            $scope.getData();

            $scope.switch = function(){
                $scope.step.name = '<?php echo $gotoStepName ?>';
            }

            <?php foreach($stepButtons as $eventName => $buttonName): ?>$scope.<?php echo $eventName?> = function(){

            }
            <?php endforeach;?>

        },
        link: function (scope, element, attrs) {}
    };
});

backend/views/generator/ng-loader-template.php
"<div class=\"loader\" data-ng-show=\"working\" style=\"position: absolute;top: 0px;bottom: 0px;left: 0px;right: 0px;height: 100% !important;width: 100% !important;\">\n"+
"<div class=\"loader-content\" style=\"position: absolute;top: 50%;left: 50%;line-height: 1;max-width: 50%;padding: 7px;-o-border-radius: 5px;border-radius: 5px;background-color: <?php echo $model->bg_color ?>;color: #ffffff;text-transform: uppercase;text-align: center;word-break: break-word;z-index: 1;\">\n"+

<?php echo $model->svg ?>

"<p style=\"margin: 2px 0px;\" data-ng-bind=\"message\" data-ng-cloak data-ng-show=\"message\"></p>\n"+
"</div>\n"+
"</div>"